# Generated by Django 5.0.6 on 2024-07-04 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_id_alter_bid_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(default='uncategorized', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='current_highest_bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='listing_is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='current_highest_bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(default='untitled', max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auction_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
