# Generated by Django 5.0.6 on 2024-07-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlistings_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='current_highest_bid',
        ),
    ]
