# Generated by Django 5.0.6 on 2024-07-09 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bid_current_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='bid_amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='buy_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='starting_bid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
