# Generated by Django 5.0.6 on 2024-07-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlistings_bid_amount_auctionlistings_bid_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='bid_time',
            field=models.DateTimeField(default='timezone.now'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='buy_price',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='starting_bid',
            field=models.FloatField(default='0'),
        ),
    ]
