# Generated by Django 5.0.6 on 2024-07-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlistings_bid_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='bid_time',
        ),
    ]
